# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20161024_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousspeaker',
            name='resume',
            field=models.CharField(blank=True, max_length=254, verbose_name='Une description rapide'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='resume',
            field=models.CharField(blank=True, max_length=254, verbose_name='Une description rapide'),
        ),
        migrations.AlterField(
            model_name='previousspeaker',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='previousspeaker',
            name='image',
            field=models.FileField(upload_to='assets/media/media/speakers', verbose_name='Image :'),
        ),
        migrations.AlterField(
            model_name='previousspeaker',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Nom du speaker'),
        ),
        migrations.AlterField(
            model_name='previousspeaker',
            name='year',
            field=models.CharField(max_length=30, verbose_name='Annee ou le speaker est passe a tedx'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.FileField(upload_to='assets/media/media/speakers', verbose_name='Image :'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Nom du speaker'),
        ),
    ]
