# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20161014_1525'),
        ('event', '0005_speaker_heure'),
    ]

    operations = [
    ]
