# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20161128_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
    ]
